### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by TheEssem** [esmBot/esmBot#2]
Here is a list of some features that I have been planning to implement or would be nice to have in esmBot. If you want to contribute, this is a good place to start.

- [ ] Parameters for image commands (for more control)
- [ ] mute command
- [ ] shake command
- [x] External upload support (for media larger than 8 MB)
- [x] resize command
- [ ] gmagik command
- [x] Tenor/Giphy/Imgur support for image commands

**Comment by oatmealine** [comment]
what does a "resize command" mean

**Comment by TheEssem** [comment]
> what does a "resize command" mean

Resizing images, tbh though the wide/stretch commands already fill this role
